{% set name = "luddite" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/luddite-{{ version }}.tar.gz
  sha256: c31ffdb2644062253c8b33087bbf1cee007fe4590bb7de513b290861f7a26cf5

build:
  entry_points:
    - luddite=luddite:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=18.0
  run:
    - colorama  # [win]
    - packaging
    - python

test:
  imports:
    - luddite
  commands:
    - pip list
    - pip check
    - luddite --help
  requires:
    - pip

about:
  home: https://pypi.org/project/luddite
  summary: Checks for out-of-date package versions
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/jumptrading/luddite

extra:
  recipe-maintainers:
    - goanpeca
    - wimglenn
